  chore/repo-tooling[m
  chore/so-form-polish[m
  chore/so-list-filter-friendly-id[m
  chore/wave-settings-description-polish[m
  feat/address-upsert[m
  feat/amend-wipes-wave-fields[m
  feat/auto-push-on-so-submit[m
  feat/cancel-and-intake-hardening[m
  feat/credit-note-cancel-on-full-return[m
  feat/customer-handler[m
  feat/delivery-note-status-push[m
  feat/dn-autopopulate-from-wave-so[m
  feat/enforce-inbound-key-length[m
  feat/erp-to-wave-api-and-ui[m
  feat/erp-to-wave-foundation[m
  feat/erp-to-wave-services[m
  feat/fee-mapping-soft-fail[m
  feat/log-success-and-manual-batch-button[m
  feat/manual-review-badge[m
  feat/manual-stock-resync[m
  feat/master-kill-switch[m
  feat/order-intake[m
  feat/outbound-order-status[m
  feat/outbound-stock-sync[m
  feat/pick-list-accepted[m
* [32mfeat/pick-list-amend-picker-reset[m
  feat/pick-list-lockdown-skip-non-wave[m
  feat/pick-list-per-product-comments[m
  feat/sales-invoice-status-push[m
  feat/scaffolding-logging-settings[m
  feat/stock-quantity-limit-mirror[m
  feat/wave-action-doctype[m
  feat/wave-product-id-resolver[m
  feat/wave-status-doctype[m
  feat/wave-tax-rules[m
  feat/webhook-endpoint-auth[m
  fix/auth-diagnostic-log[m
  fix/dispatcher-source-doctype-plumbing[m
  fix/inbound-auth-logs-and-charset[m
  fix/manual-review-banner-draft-only[m
  fix/order-status-correct-endpoint[m
  fix/order-status-event-kwarg-collision[m
  fix/order-status-soft-skip-terminal[m
  fix/sync-log-clickable-link[m
  fix/test-isolation-and-always-protect-child-tables[m
  fix/wave-order-id-fixture-unique[m
  fix/wave-settings-persistence[m
  fix/wave-settings-protect-child-tables[m
  fix/wave-sync-log-step-and-job-id[m
  main[m
